# Generated by Django 2.2.6 on 2019-10-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='images.Tag'),
        ),
    ]
